name: PrimoPur Organic Farms
favicon: null
layout_spectrum: 0.9191489
typography_spectrum: 0.1021277
title: Primopur organic farms
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#75A8E7'
    - '#88923B'
    - '#0B1306'
    - '#293332'
    - '#DDE5F2'
  brandStrength: 0.2808511
  lightness: 0.7127659
  saturation: 0.5404255
  rhythmicContrast: 0.4446808
purpose: []
