layout_spectrum: 0.05649241
color:
  saturation: 0.2849916
  lightness: 0
  brandStrength: 0.06576729
  brandColors:
    - '#75A8E7'
    - '#88923B'
    - '#0B1306'
    - '#293332'
    - '#DDE5F2'
  rhythmicContrast: 0.1416526
typography_spectrum: 0.113828
name: PrimoPur Organic Farms
