title: Primopur organic farms
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.4425532
  brandStrength: 0.1723404
  lightness: 0.8404256
  brandColors:
    - '#75A8E7'
    - '#88923B'
    - '#0B1306'
    - '#293332'
    - '#DDE5F2'
  rhythmicContrast: 0.3595745
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: PrimoPur Organic Farms
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.1148936
layout_spectrum: 0.9489362
